student =["Talha" , "Hassan" , "Mohsin" , "Saif" , "Babar"]
print (student [0:4])
teacher = ["Zafar" , "Umar" , "Rashid"]
teacher.append("Rayan")
teacher.append("ajmal")
teacher.extend(["Hamza" , "jawad" , "wahad" , "hanan" , "nawab"])
print(student[1])
student.insert(5, "Haris")
print(student)
hfza=student.index("Babar")
print(hfza)
uls = student.copy()
print(uls)
uls.extend(["Rizwan" , "khan"])
print(uls)
print(type(student))
print(len(student))
class1 = [teacher[2], student[2:]]; print(class1)
class2 = [teacher[1] , student[3:5]] ; print(class2)